### ISSUE TITLE
shared data

### ISSUE THREAD

**Issue by bastianh** [hxjo/fastapi-inertia#1]
Hi!

I wonder how the flash messages in shared data are handled .. the protocol page says 

>  If "flash" session data exists when a 409 Conflict response occurs, Inertia's server-side framework adapters will automatically reflash this data.

not sure how to implement that, though.

**Comment by bastianh** [comment]
guess doing it similar to the django implementation would work

**Comment by hxjo** [comment]
Hey !
Could you share an example of what you'd expect and how it actually behaves ?
Thanks

**Comment by hxjo** [comment]
Tbh considering when request is stale, only a 409 is sent to the frontend, hence "asking" for a new request to be performed, I don't really get their comment saying the server will reflash this data.
On another point, I agree the way I've implemented the share feature is not very useful.
I'm working on handling SSR currently, hopefully by next week I can rework the sharing process so it makes more sense (through extending the inertia middleware for instance, tbd)
Given Django uses django.contrib.messages to handle "flash", I believe a simple function/class which sets session httponly with short expires cookies on the request (so it's being passed around on redirects) could do the trick.

But if you have an example of what you're trying to achieve (code or pseudo -code, or even a good explanation), I'd really like to hear it so I can adjust if it makes sense to me ! 
Have a good day

**Comment by bastianh** [comment]
The idea for flash messages ist that the data is only added to the next request and deleted then .. like a success notification or something like that.

So the problem is that if this next request is cancelled by the 409 the user will never see the success message... that's why for example the Django implementation keeps the messages in the session and is added to the next message again.


I think I'll try to do the whole inertia implementation completely different without a middleware, because the fastapi dependency injection allows a, in my opinion much nicer way to do it. ... I'll add an example here from my working prototype .. it's probably not working without some tweaking but so you can see my idea .)

**Comment by bastianh** [comment]
this is from my prototype ... it raises an error before the routing function is even executed if the version of the backend changes...

```python


class InertiaVersionConflict(Exception):
    def __init__(self, url):
        self.url = url

@lru_cache()
def get_template_html():
    if settings.debug:
        body_module = '\n\t\t<script type="module" src="/src/main.js" defer></script>'
        head_module = '<script type="module" src="/@vite/client"></script>'
    else:
        head_module = ""
        with open(os.path.join(settings.static_folder, ".vite", "manifest.json"), "r", encoding="utf-8") as file:
            jdata = orjson.loads(file.read())
            for data in jdata.values():
                if "isEntry" in data:
                    head_module += f'<script type="module" crossorigin src="/{data["file"]}"></script>'
                    for css in data["css"]:
                        head_module += f'<link rel="stylesheet" crossorigin href="/{css}">'
        body_module = ""

    return Template(
        f"""<!doctype html>\n<html>\n\t<head>\n\t\t<meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
        {head_module}\n\t</head>\n\t<body>\n\t\t<div id="app" data-page='$page_data'></div>{body_module}\n\t</body>\n</html>"""
    )



# dependency that creates a json or html response depending on header

class InertiaDep:
    def __init__(self, request: Request):
        self._request = request
        self._props = {}
        self._current_version = settings.git_rev

        # check version before the route is even executed
        if self._request.method == "GET" and "x-inertia" in self._request.headers and self._request.headers.get("x-inertia-version") != settings.git_rev:
            raise InertiaVersionConflict(self._request.url)

    def share(self, **props):
        self._props.update(props)

    def _get_inertia_content(self, component:str, encode: bool = False):
        content = orjson.dumps({
            "component": component,
            "props": self._props,
            "url": str(self._request.url),
            "version": self._current_version,
        }, option=orjson.OPT_NON_STR_KEYS | orjson.OPT_SERIALIZE_NUMPY | orjson.OPT_OMIT_MICROSECONDS)
        if encode:
            return content.decode(encoding="utf-8").replace("'", "&#x27;")
        else:
            return content


    def __call__(self, component, **props):
        if props:
            self._props.update(props)

        if "x-inertia" not in self._request.headers:
            template = get_template_html()
            return HTMLResponse(template.substitute(page_data=self._get_inertia_content(component, True)))

        content = self._get_inertia_content(component)
        return Response(content, media_type="application/json", headers={"X-Inertia": "true"})


Inertia = Annotated[InertiaDep, Depends(InertiaDep)]

# ------------------------------

# example dependency that adds a shared prop
def login_required(request: Request, inertia: Inertia):
    if request.user:
        # here we add user as a prop to all requests using this dependency
        inertia.share(user=request.user)
        return request.user

app = FastAPI()

@app.exception_handler(InertiaVersionConflict)
def exception_handler(request: Request, exc: InertiaVersionConflict):
    return Response(status_code=status.HTTP_409_CONFLICT, headers={"X-Inertia-Location": str(exc.url)})


@app.get("/index")
def index(inertia: Inertia):
    return inertia("Home", someProp="hello world")


# all routes of this router requires a valid user
router = APIRouter(dependencies=[Depends(login_required)])

@router.get("/test")
def test(inertia: Inertia):
    return inertia("Test", someProp="hello world")


app.include_router(router)
```

**Comment by hxjo** [comment]
I like your way ! I agree using a middleware is not great given the dependency system FastAPI gives us.
At first, I just re-implemented the way Django does it, without thinking much about it.
I think I'll work on doing it using the dependency system like you did !

**Comment by hxjo** [comment]
I finished implementing it as a dependency, I just need to make the settings more accessible and I'll be good.
As for the reflash when redirecting, I actually dont see why we would even need to reflash.

Let's say to implement a flash system, we set a session middleware and we can flash some data. On consumption, we pop from this session flash.

We just need to consume only on rendering, and not consume it otherwise.
Like when calling inertia.render, now we consume the flash and pass it to the props 

This solves the problem as:
1. 409 don't render, so the flash data is not consumed
2. Any other redirect do not render either, so flash data is not consumed

Or am I missing something here?

**Comment by bastianh** [comment]
Yes... another thing to consider next would be the partial upgrades... in the middleware solution it's quite complicated with lambdas, because the render function can't know if an partial update is requested, but with the dependency solution it might be possible to check that in the render function and react there. I have not looked into that yet.

**Comment by hxjo** [comment]
I'll take a look at it ! 
Thanks for your comment, I'm a big fan of inertia and I'd love to provide a stable package for the community, so your comments are of great help.

**Comment by hxjo** [comment]
I'll close this discussion as I found a way to implement the points mentioned above. Don't hesitate to reopen one if you feel like something's missing! 
Thanks for your input.
