### ISSUE TITLE
# Enhancements proposal

### ISSUE THREAD

**Issue by ndilsou** [hxjo/fastapi-inertia#17]
Hi,

First, I want to give a big shout-out for the work on this library! I've been looking for something like this for quite some time now. Please, take all my suggestions below as a token of appreciation for doing the work of implementing the Inertia protocol in FastAPI. :)

I forked the library and made several changes that I believe would be beneficial. I propose merging these changes back into your main branch. This issue is an overview of the changes for your review, and we can discuss any requirements you may have for merging. The changes are currently on the 'develop' branch of my fork, although I haven't updated the README yet. I do have a plan to break these into multiple PRs to make the integration easier.

Summary of the enhancements:
- Replace raw string matching with BeautifulSoup lookup in unit tests
- Implement manifest file caching and enhance Vite Manifest dict typing
- Switch from Requests to HTTPX for SSR.
- Add user configuration options for:
	- Entrypoint filename
	- Frontend root directory in development
	- Optional `assets_prefix` in production
	- Deprecate the `use_typescript` field
	- 
- Add support for Jinja2:
	- Accept a Jinja2Templates instance in the InertiaConfig
	- Allow user to specify a root template filename
	- Create a Jinja extension to process the HTML 
	 - Adapt internal logic of the Inertia class to using Jinja2
- Introduce an 'examples' folder with examples for React and React-SSR (I can easily do the same for Vue and Svelte).

All these changes are implemented in my fork, and all tests are passing. You can pull the fork and test for yourself by running the examples. Keep reading for details on each enhancement proposed.
## Suggested enhancements
Please note that I can write a migration guide for each change that I marked as breaking to help your existing users transition smoothly...
### Replace raw string matching with BeautifulSoup lookup in unit tests
**non breaking**
This is preliminary work for other enhancements. By using BeautifulSoup, we can be more precise in our tests, which is needed when the HTML is produced by Jinja.
### Implement manifest file caching and enhance Vite Manifest dict typing
**non breaking**
The current implementation opens and reads the manifest on each request, which is inefficient. This change adds an LRU cache to keep the manifest in memory. Additionally, I derived a stricter TypedDict for the JSON record from the manifest file using the Vite documentation.
### Switch from Requests to HTTPX for SSR
**breaking**
The current implementation uses Requests to call the SSR server, which blocks the event loop with `requests.post`. This can lead to performance issues under higher load as it takes an entire thread away.

This enhancement swaps Requests for an HTTPX AsyncClient. HTTPX is already the basis for the FastAPI TestClient. We leverage FastAPI's lifespan and request.state object to handle the lifecycle of the async client cleanly and inject it into the Inertia dependency.

### Update the InertiaConfig to make the library more configurable
**breaking**
This is actually what led me to fork this at first: I needed to be able to use a different root directory for my frontend (I usually use something else than src).

This enhancement allows developers to set the following:
- Entrypoint filename (e.g., `main.tsx`), eliminating the need for the `use_typescript` config option.
- Frontend root directory for development.
- Optional `asset_prefix` for production to serve static files outputted by the Vite build.

### Add support for Jinja2
**breaking**
This enhancement includes:
- make the `index.html` explicit to the developer. This would allow them to add any extra tag needed.
- adding a config to specify the root template filename if not `index.html`
- receiving a `Jinja2Templates` instance in the config.
- creating a Jinja extension to define two new tags that can be put in the `index.html`: `{% inertia_head %}` and `{% inertia_body %}`.
- Adapt the internals of the Inertia class to delegate HTML manipulation responsibility to the extension and to Jinja.
- This also includes properly inserting the vite React Refresh script inside the HTML if the `is_react` flag is true in the config.

Exposing the entrypoint HTML template aligns with the Laravel reference implementation. And since Jinja is the de-facto default templating engine for FastAPI apps anyway, adding it as a dependency is reasonable.
###  Introduce an 'examples' folder
**non breaking**
This is simply to help with adoption of the library by other. I've started an examples folder with basic implementations to help FastAPI users grok how to use fastapi-inertia in their projects. I had to try a few things before getting SSR to work... hopefully the example saves the next developer some time.

I'm used to React so I currently have examples for React and React with SSR. I can easily add similar examples for Vue and Svelte.

## PR Submission Order
If there's interest in these changes, I can break down the change from my fork into a separate feature branch for each sections above and submit in the following order. I want to make it easier for you to review, suggest edits, and merge each change sequentially.

So the plan would be:
1. Replace raw string matching with BeautifulSoup lookup in unit tests
2. Implement manifest file caching and enhance Vite Manifest dict typing
3. Switch from Requests to HTTPX for SSR.
4. Add new configuration options.
5. Add support for Jinja2
6. Introduce an example folder

I'm really hoping this gets you excited and you're open to work on this together.

**Comment by ndilsou** [comment]
Here I am actually forgetting to give a link to my fork.

Link to said branch: https://github.com/ndilsou/fastapi-inertia/tree/develop

**Comment by hxjo** [comment]
Hello !

First of all, thanks for the time spent enhancing this library.

From the changes listed, I see only good things so I mostly agree to what you propose.

As for the examples, I agree we could move them to this repo ; I made a bunch of examples for vue in another repo but it's quite far to reach.

Your PRs are very welcome, as long as they come with README changes, CHANGELOG updates and, if breaking, a migration guide.

I don't have any CD so I'll need to perform the publishes to PyPI manually 

Thank you very much for your time !

**Comment by ndilsou** [comment]
Hey, just a heads up this is still on my radar. I've just been surprisingly busy. I'll keep your guidelines in mind and probably start working on it over the weekend.

Thanks!

**Comment by hxjo** [comment]
Hello @ndilsou ,

I implemented most of your changes;

I did not:
- Add the `is_react` option to InertiaConfig nor all the code related to it
  - I dislike the idea of having to maintain framework-specific code parts in the repository. I believe those can be added in the examples part, as all parts of the library can be overridden if need be
- Add the examples from your repository
  - Those are your examples ; please feel free to create a PR to integrate them with the repo !

I'll close this issue
Have a good day :)
